// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpubAvaEaiegi6waa5pxnjHzQBfVPTnPE',
    appId: '1:450032759551:android:49e0b308f0cde968f352ca',
    messagingSenderId: '450032759551',
    projectId: 'e-commerce-app-2dc94',
    storageBucket: 'e-commerce-app-2dc94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHt-Ih9YVMc-1dZJoP6s3HCkvWb6vh1B8',
    appId: '1:450032759551:ios:119728c1db1a0966f352ca',
    messagingSenderId: '450032759551',
    projectId: 'e-commerce-app-2dc94',
    storageBucket: 'e-commerce-app-2dc94.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
